---
# Default values for petclinic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: registry.labbi.lab/petclinic
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''
imagePullSecrets:
  name: regcred
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: petclinic
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
deployment:
  postStart: {}
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: webapprouting.kubernetes.azure.com
  annotations: {}
  hosts:
    - host: labbi.lab
      paths:
        - path: /
          pathType: Prefix
  tls: []
volumeMounts:
  - name: regcert
    mountPath: /usr/local/share/ca-certificates/server.crt
    readOnly: false
    subPath: tls.crt
  - name: regcert
    mountPath: /usr/local/share/ca-certificates/server.key
    readOnly: false
    subPath: tls.key
volumes:
  - name: regcert
    secret:
      secretName: nexus-tls
      defaultMode: 0400
postgresql:
  enabled: true
  fullnameOverride:
  auth:
    username: petclinic
    password: petclinic
    database: petclinic
  service:
    clusterIP:
  primary:
    persistence:
      enabled: true
      storageClass:
      accessModes: [ReadWriteOnce]
      size: 8Gi
