---
# Default values for petclinic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: registry.labbi.lab/petclinic
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''
imagePullSecrets:
  name: regcred
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: petclinic
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
deployment:
  postStart: {}
    # command: [/bin/sh, -c, update-ca-certificates]
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/enable-directory-listing: 'false'
    nginx.ingress.kubernetes.io/limit-connections: '20'
    nginx.ingress.kubernetes.io/limit-rps: '5'
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($scheme !~* ^(http|https)$) { return 444; }
  hosts:
    - host: labbi.lab
      paths:
        - path: /
          pathType: Prefix
  tls: []
# volumeMounts:
#   - name: regcert
#     mountPath: /usr/local/share/ca-certificates/server.crt
#     readOnly: false
#     subPath: tls.crt
#   - name: regcert
#     mountPath: /usr/local/share/ca-certificates/server.key
#     readOnly: false
#     subPath: tls.key
#   - name: regcert
#     mountPath: /etc/ssl/certs/server.crt
#     readOnly: false
#     subPath: tls.crt
# volumes:
#   - name: regcert
#     secret:
#       secretName: nexus-tls
#       defaultMode: 0400
postgresql:
  enabled: true
  fullnameOverride:
  auth:
    username: petclinic
    password: petclinic
    database: petclinic
  service:
    clusterIP:
  primary:
    persistence:
      enabled: true
      storageClass:
      accessModes: [ReadWriteOnce]
      size: 8Gi
