---
# Default values for petclinic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: mahmoudk1000/petclinic
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''
imagePullSecrets: [docker-credentials]
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: petclinic
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: webapprouting.kubernetes.azure.com
  annotations: {}
  hosts:
    - host: labbi.lab
      paths:
        - path: /
          pathType: Prefix
  tls: []
postgresql:
  enabled: true
  fullnameOverride:
  auth:
    username: petclinic
    password: petclinic
    database: petclinic
  service:
    clusterIP:
  primary:
    persistence:
      enabled: true
      storageClass:
      accessModes: [ReadWriteOnce]
      size: 8Gi
