---
# Default values for petclinic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.labbi.lab:30443/petclinic
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''
imagePullSecrets:
  name: regcred
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: petclinic
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
deployment:
  postStart: {}
    # command: [/bin/sh, -c, update-ca-certificates]
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/enable-directory-listing: 'false'
    nginx.ingress.kubernetes.io/limit-connections: '20'
    nginx.ingress.kubernetes.io/limit-rps: '5'
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($scheme !~* ^(http|https)$) { return 444; }
  hosts:
    - host: labbi.lab
      paths:
        - path: /
          pathType: Prefix
  tls: []
volumeMounts: {}
postgresql:
  enabled: true
  fullnameOverride:
  auth:
    username: petclinic
    password: petclinic
    database: petclinic
  service:
    clusterIP:
  # persistence:
  #   storageClass: manual
  #   size: 5Gi
  primary:
    persistence:
      enabled: true
      storageClass: manual
      accessModes: [ReadWriteOnce]
      size: 5Gi
