---
apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command: [sleep]
      args: [infinity]
      volumeMounts:
        - name: docker-cfg
          mountPath: /kaniko/.docker
    - name: maven
      image: maven:3.9.7-amazoncorretto-17
      command: [sleep]
      args: [infinity]
    - name: helm
      image: alpine/helm:latest
      command: [sleep]
      args: [infinity]
  volumes:
    - name: docker-cfg
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
