library "jenkins-shared-library@stable"

def appName = 'petclinic'
def regDest = 'nexus-nexus-repository-manager-docker-5000.nexus.svc.cluster.local:5000'
def pomVersion = 'latest'

pipeline {
    agent {
        kubernetes {
            inheritFrom 'default'
            yamlFile '.pipeline/podtemplate.yaml'
            defaultContainer 'jnlp'
        }
    }

    stages {
        stage('SonarQube Analysis') {
            steps {
                container('maven') {
                    withSonarQubeEnv(installationName: 'SonarQubeServer', credentialsId: 'SonarQubeToken') {
                        sh label: "Running SCA Test",
                            script: "./mvnw clean verify sonar:sonar -Dsonar.projectKey=petclinic -Dsonar.projectName='petclinic'"
                    }
                    script {
                        gitSha = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                    }
                }
            }
        }
        stage('Build Artifact') {
            steps {
                container('maven') {
                    script {
                        pomVersion = sh(script: './mvnw help:evaluate -Dexpression=project.version -q -DforceStdout', returnStdout: true).trim()
                        sh label: "Building Artifact",
                            script: "./mvnw package -DskipTests"
                    }
                }
            }
        }
        stage('Building Image Using Kaniko') {
            steps {
                container (name: 'kaniko', shell: '/busybox/sh') {
                    script {
                        kanikoBuildPush(regDest, appName, pomVersion)
                    }
                }
            }
        }
        stage('Deploy Development') {
            when {
                branch 'dev'
            }
            steps {
                container('helm') {
                    dir('.pipeline/helm') {
                        script {
                            helmInstall(appName, "dev-values", "${pomVersion}_${gitSha}", "${appName}-dev")
                        }
                    }
                }
            }
        }
        stage('Deploy Stage') {
            when {
                branch 'release'
            }
            steps {
                container('helm') {
                    dir('.pipeline/helm') {
                        script {
                            helmInstall(appName, "stg-values", "${pomVersion}_${gitSha}", "${appName}-stg")
                        }
                    }
                }
            }
        }
        stage('Deploy Production') {
            when {
                branch 'main'
            }
            steps {
                container('helm') {
                    dir('.pipeline/helm') {
                        script {
                            helmInstall(appName, "prd-values", "${pomVersion}_${gitSha}", "${appName}-prd")
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
