library "jenkins-shared-library@stable"

def appName = 'petclinic'
def regDest = 'mahmoudk1000' // 'nexus-nexus-repository-manager.nexus.svc.cluster.local:8081/docker'
def pomVersion = 'latest'

pipeline {
    agent {
        kubernetes {
            inheritFrom 'default'
            yamlFile '.pipeline/podtemplate.yaml'
            defaultContainer 'jnlp'
        }
    }

    stages {
        stage('SonarQube Analysis') {
            steps {
                container('maven') {
                    withSonarQubeEnv(installationName: 'SonarQubeServer', credentialsId: 'SonarQubeToken') {
                        sh label: "Running SCA Test",
                            script: "./mvnw clean verify sonar:sonar -Dsonar.projectKey=petclinic -Dsonar.projectName='petclinic'"
                    }
                }
            }
        }
        stage('Build Artifact') {
            steps {
                container('maven') {
                    script {
                        pomVersion = sh(script: './mvnw help:evaluate -Dexpression=project.version -q -DforceStdout', returnStdout: true).trim()
                        sh label: "Building Artifact",
                            script: "./mvnw package -DskipTests"
                    }
                }
            }
        }
        stage('Building Image Using Kaniko') {
            steps {
                container (name: 'kaniko', shell: '/busybox/sh') {
                    script {
                        kanikoBuildPush(regDest, appName, pomVersion)
                    }
                }
            }
        }
        stage('Deploy Devleopment') {
            when {
                branch 'dev'
            }
            steps {
                container('helm') {
                    dir('.pipeline/helm') {
                        sh label: "Deploying to Development",
                            script: '''
                                helm dependency update .
                                helm upgrade --install ${appName} . -f dev-values.yaml --set image.tag=${pomVersion} -n ${appName}-dev
                            '''
                    }
                }
            }
        }
        stage('Deploy Stage') {
            when {
                branch 'release'
            }
            steps {
                container('helm') {
                    dir('.pipeline/helm') {
                        sh label: "Deploying to Development",
                            script: '''
                                helm dependency update .
                                helm upgrade --install ${appName} . -f tst-values.yaml --set image.tag=${pomVersion} -n ${appName}-tst
                            '''
                    }
                }
            }
        }
        stage('Deploy Production') {
            when {
                branch 'main'
            }
            steps {
                container('helm') {
                    dir('.pipeline/helm') {
                        sh label: "Deploying to Development",
                            script: '''
                                helm dependency update .
                                helm upgrade --install ${appName} . -f prd-values.yaml --set image.tag=${pomVersion} -n ${appName}-prd
                            '''
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
