---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-ca
  namespace: kube-system
data:
  cert.crt: |
    -----BEGIN CERTIFICATE-----
    MIIECTCCAvGgAwIBAgIUXhC6d1es/nSCeFQJqDyujbIkzOcwDQYJKoZIhvcNAQEL
    BQAwgZMxCzAJBgNVBAYTAkVHMRMwEQYDVQQIDApBbGV4YW5kcmlhMRMwEQYDVQQH
    DApBbGV4YW5kcmlhMQ4wDAYDVQQKDAVMYWJiaTEPMA0GA1UECwwGRGV2T3BzMRIw
    EAYDVQQDDAlsYWJiaS5sYWIxJTAjBgkqhkiG9w0BCQEWFm1haG1vdWRrMTAwMEBn
    bWFpbC5jb20wHhcNMjQwOTA5MTExOTExWhcNMjkwOTA4MTExOTExWjCBkzELMAkG
    A1UEBhMCRUcxEzARBgNVBAgMCkFsZXhhbmRyaWExEzARBgNVBAcMCkFsZXhhbmRy
    aWExDjAMBgNVBAoMBUxhYmJpMQ8wDQYDVQQLDAZEZXZPcHMxEjAQBgNVBAMMCWxh
    YmJpLmxhYjElMCMGCSqGSIb3DQEJARYWbWFobW91ZGsxMDAwQGdtYWlsLmNvbTCC
    ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALwzmD7pG/+lzURGKRf8v9GV
    Kv2V0GDEnO+p4dGHtf/HU2D8GaYArsUtuMcM60/fndjsz9ZgxVa9GfnRL5TyeB9w
    o+h8Bwsqv5/846xEeFjYQT/ZeehM/xcVmBVm493hSvr7jvv2PaeVfot5SnXsd1PA
    F/NGMKmX2hxOzuEu4PisBOZ6FWhs+u0xEhv2KqIyBv7djz56iPKVP/K+OfAjsxiV
    wA4yFbS46eZ8zmB9Yz6yO5gMShcJBpvr3tzyBWEkup5q+/Gn1dtiOSKC+o55u0Ac
    nIya0fdp9MRl3BDz+68cu13CvC8uf5AZMS0w3EKWpmPB/mq/SNxfs0jF7obiEnEC
    AwEAAaNTMFEwHQYDVR0OBBYEFJDiTcflqIYLZydo6ptJ21NWyV3OMB8GA1UdIwQY
    MBaAFJDiTcflqIYLZydo6ptJ21NWyV3OMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI
    hvcNAQELBQADggEBAGxsTupWGB1XnDLqxDtlm/7leOHmM6jrHlYpytJnzcqRPXEL
    GIjfTFgWX+uTMP1vdkqdTIUIUdDLipNxUiFkdUSYdV4pjBanK450RFMEKAwrVN2t
    eiHt2QcVN5SKMWpFfjXbmlz0sa+5gg26LxwGpOnayLmWCkRsiKAXk51WJqoeKJul
    ytYPrYJ6jzFxwUagVeGejCYd7qYh8cOajhJgrtD4WWSXErsv2TtScvxxWDI5AguN
    wRwC7thUg1bPHWLcAos4xlNFB8C3NktJbWDdVENr7FPcSdA23co53Ae9BTk0d6J7
    j5XV/jUBo4Myc10bWoX+oWgoABDsEhqlexXJpxk=
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: kube-system
data:
  cert_install.sh: |
    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/cert.crt &&
    echo "$TRUSTED_CERT" > /etc/ssl/certs/cert.crt &&
    update-ca-certificates &&
    systemctl restart containerd
  hosts.sh: |
    echo "51.144.158.233 registry.labbi.lab" >> /etc/hosts
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: nodes-injector
  labels:
    k8s-app: nodes-injector
spec:
  selector:
    matchLabels:
      k8s-app: nodes-injector
  template:
    metadata:
      labels:
        k8s-app: nodes-injector
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: cert-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(CERT_SCRIPT)]
          image: debian
          env:
            - name: TRUSTED_CERT
              valueFrom:
                configMapKeyRef:
                  name: trusted-ca
                  key: cert.crt
            - name: CERT_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: cert_install.sh
          securityContext:
            privileged: true
        - name: host-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(HOSTS_SCRIPT)]
          image: debian
          env:
            - name: HOSTS_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: hosts.sh
          securityContext:
            privileged: true
      containers:
        - name: wait
          image: k8s.gcr.io/pause:3.1
