---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-ca
  namespace: kube-system
data:
  cert.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEDzCCAvegAwIBAgIUdtWxk2G/rVdt2dDDly5pmtfzBDIwDQYJKoZIhvcNAQEL
    BQAwgZYxCzAJBgNVBAYTAkVHMQ4wDAYDVQQIDAVFZ3lwdDETMBEGA1UEBwwKQWxl
    eGFuZHJpYTENMAsGA1UECgwEQVRPUzEPMA0GA1UECwwGRGV2T3BzMRswGQYDVQQD
    DBJyZWdpc3RyeS5sYWJiaS5sYWIxJTAjBgkqhkiG9w0BCQEWFm1haG1vdWRrMTAw
    MEBnbWFpbC5jb20wHhcNMjQwOTA5MTU1NTQyWhcNMjkwOTA4MTU1NTQyWjCBljEL
    MAkGA1UEBhMCRUcxDjAMBgNVBAgMBUVneXB0MRMwEQYDVQQHDApBbGV4YW5kcmlh
    MQ0wCwYDVQQKDARBVE9TMQ8wDQYDVQQLDAZEZXZPcHMxGzAZBgNVBAMMEnJlZ2lz
    dHJ5LmxhYmJpLmxhYjElMCMGCSqGSIb3DQEJARYWbWFobW91ZGsxMDAwQGdtYWls
    LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJtzpfD9O7FcqCuf
    JFDK058N2tOH3eJWNxlbPI9tRm3JFeVOJiUb7jKuCwZAmV5BrUgOd9gnuoiAjpDh
    zIx3xAeKAgVTkHZcjkL2rom6tBPEq2obb7XD8UIQUfLpCue/ajUwywqa3PSGO3O8
    naIwSmwU2t0GSvRA8YaVSCStMRThhTnqOodBJWFG3nG3kqqClmVMv/ts2IedTokS
    VcN3Ohu4KwSy+CEjw3gr2R+cetAxo9dWFSNzPFZco/KU6MOMTQvZFDTXd9ujiz4a
    kby/wNbbnPr9Fp0fg9nmMpt7rsDu7wmnnRysPc7RKskp2ZJXzEzHtHQyx9JXlLCb
    o//sjJsCAwEAAaNTMFEwHQYDVR0OBBYEFPCdkcgG1KVpBP07DYnign7SrB2xMB8G
    A1UdIwQYMBaAFPCdkcgG1KVpBP07DYnign7SrB2xMA8GA1UdEwEB/wQFMAMBAf8w
    DQYJKoZIhvcNAQELBQADggEBAFt7Nj+uFElaEsYiO/a3FlLR8Lj3S09X8CVyV5bJ
    KnDdD2DDv2DZ+opPO496wRIq1H6GRIrwRb8tEDG6Vg8Og4ohhNL166WDHmmE1hHa
    3XBVCr3rjwXB2wguTuTaB/gTznGZgNxarmkZyFraLbacBG7pDplSamTRqnrS2rXk
    M3CM5gQc2SMLXXS/HCT7/GvFRMrQh5+ijIsCSySP99ZhHxmFYie79lTW+pgtabB7
    On9X3hn+o28yhnff0fErtkQOxmFZFG1yk0VlP68NbN+fonZj8U+gI5KOxo6w2q1q
    6jqMMwTyY/iO+3S6fbUM8LlQR7lCUGIqTNTGNmt1NQSUiz0=
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: kube-system
data:
  cert_install.sh: |
    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/cert.crt &&
    echo "$TRUSTED_CERT" > /etc/ssl/certs/cert.crt &&
    update-ca-certificates &&
    systemctl restart containerd
  hosts.sh: |
    echo "51.144.158.233 registry.labbi.lab" >> /etc/hosts
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: nodes-injector
  labels:
    k8s-app: nodes-injector
spec:
  selector:
    matchLabels:
      k8s-app: nodes-injector
  template:
    metadata:
      labels:
        k8s-app: nodes-injector
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: cert-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(CERT_SCRIPT)]
          image: debian
          env:
            - name: TRUSTED_CERT
              valueFrom:
                configMapKeyRef:
                  name: trusted-ca
                  key: cert.crt
            - name: CERT_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: cert_install.sh
          securityContext:
            privileged: true
        - name: host-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(HOSTS_SCRIPT)]
          image: debian
          env:
            - name: HOSTS_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: hosts.sh
          securityContext:
            privileged: true
      containers:
        - name: wait
          image: k8s.gcr.io/pause:3.1
