---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-ca
  namespace: kube-system
data:
  cert.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFzzCCA7egAwIBAgIUIYpOVrxU1j4dBQZe9xejyH4TYqwwDQYJKoZIhvcNAQEL
    BQAwbzELMAkGA1UEBhMCRUcxDjAMBgNVBAgMBUJFVE5BMQ4wDAYDVQQHDAVFR1lQ
    VDENMAsGA1UECgwEQVRPUzEgMB4GA1UECwwXU21lIE9yZ2FuaXphdGlvbmFsIFVu
    aXQxDzANBgNVBAMMBlJvb3RDQTAeFw0yNDA5MDkxMzAxMTRaFw0zNDA5MDcxMzAx
    MTRaMG8xCzAJBgNVBAYTAkVHMQ4wDAYDVQQIDAVCRVROQTEOMAwGA1UEBwwFRUdZ
    UFQxDTALBgNVBAoMBEFUT1MxIDAeBgNVBAsMF1NtZSBPcmdhbml6YXRpb25hbCBV
    bml0MQ8wDQYDVQQDDAZSb290Q0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
    AoICAQC3gus7bR+1yk2QEUlbFFn1AxdasKL+i2zdoBddG1r/XAzQkqGSF7ngmWfD
    9ugoK8k6PMHLgkFU0Y1Oiy+ggIQMY4s0XDIPUY/7vCdkD3aC04eSniuLW89Ok+lV
    MkCXPEzKYoJ25dsIFHrhfeP5YRiE/ZzqSbWtvWOpkiQqcb4ANdJ59QoRLmlgn85N
    CFW4tPHlIeJvm8ZkK6t+TpfXBVzkVp8Y9XEUcRZff3NXbQ8FM8bVA3J0KZ3dyBIw
    hvCahcjxgMZbf+kgzOS/5dplqcfG1bWZrw83y2k6IDU6Eept0voy22ZwXEvLYNz5
    R2NR7PIx3iG7wi6fpIt6sKtlyC9Y87HK9k6IWdgmEoH9QJ5JBLTSmyJYOzpHIe6z
    FXDe0geBD7M2jyd2IAxk8+j7C5NjxTlj5TygYqce6XN7tuXyxv43DTNPWBDFMyg/
    BhmXeJRCCrOPU1EE39sRsX7pMtwv7ZP4/3Sh4OPbCx4hu8XzZv//zrIx40nYKgSt
    px1lMSvG/bYhGdxCcxwhxdX9MT0d0VZ6KteurBCicF9YHHAj7+eIsOt7DPQpTuDB
    Mhuy7ch+RxUSnKBYxyvwtclLIhTppnI2w7Zwkn6I2dPxbPunrmSxzBEExURE/BCN
    RCGOXxKwe8dWQ2FHsB2XsA9FSS4PEZsvFV2uDJup+qrE0TlU1wIDAQABo2MwYTAd
    BgNVHQ4EFgQUOUMk60XX37cWisxuaMSfWo6YUV0wHwYDVR0jBBgwFoAUOUMk60XX
    37cWisxuaMSfWo6YUV0wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYw
    DQYJKoZIhvcNAQELBQADggIBAJDK2TqGler2TvbvaiocngtLdvOMi0+dAIn4S0vo
    gtIwZtbZezTvyK3/zPiDEq81WfTQpeOOx6mB146gsqTrrHg0nVkjBS5qJdeYZf3X
    SQJBjxgWWyCw9sXMa23xySsh4FFH1M5o50S5oSEE0Hi1GvIL7K+pgGekF/5KTH/0
    TP7DoesI287+Yv0lpVWThTfT32rPCWK+WF+EvWUZg4HgwCGRTDOIKDiDzrLMCW2D
    bXaF/quNGlTglMu6f+DFUNiE4GfFqq28frjfMt80FXnW7U6/Bde63haV+tGG5XTT
    foJQGHoddFOe/3T7wxiMGs5PTiOI3BsmHEwwynpFNdBBSwKZQBSrgUlBD+ee9KNe
    9o/UlrjSndCCf1HsUxJTQsRyg2+wv2fNgHtFKE6meuhNTIOhGmVUG/B1HzWgc+XL
    38AcF1fCCNh/PxIooMgja3wyFBRuMXzbzalnBn8TQH2/5ct2Ze2lS1llHZ4jQoVJ
    +5iBukodHfe0L2KqmeJL+uDm8zvZHzkRYDnLYokGLNH/rjffJhr9F4ovgLnr+O8K
    s/J8uN19GSP9y9jMcVeIFkPPPcmV1L7TuymAtHMSLjCYkCATWiZleG8pIFsJgSws
    f93PI36TxEz+aF8VAlzFWbPLzJFnoLW9QksHT4hB7PnALTOwZmBnJtd5ScdWu4E5
    tUnt
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: kube-system
data:
  cert_install.sh: |
    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/cert.crt &&
    echo "$TRUSTED_CERT" > /etc/ssl/certs/cert.crt &&
    update-ca-certificates &&
    systemctl restart containerd
  hosts.sh: |
    echo "51.144.158.233 registry.labbi.lab" >> /etc/hosts
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: nodes-injector
  labels:
    k8s-app: nodes-injector
spec:
  selector:
    matchLabels:
      k8s-app: nodes-injector
  template:
    metadata:
      labels:
        k8s-app: nodes-injector
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: cert-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(CERT_SCRIPT)]
          image: debian
          env:
            - name: TRUSTED_CERT
              valueFrom:
                configMapKeyRef:
                  name: trusted-ca
                  key: cert.crt
            - name: CERT_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: cert_install.sh
          securityContext:
            privileged: true
        - name: host-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(HOSTS_SCRIPT)]
          image: debian
          env:
            - name: HOSTS_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: hosts.sh
          securityContext:
            privileged: true
      containers:
        - name: wait
          image: k8s.gcr.io/pause:3.1
