---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-ca
  namespace: kube-system
data:
  cert.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGXzCCBEegAwIBAgIUEgQhXd/98yYpcAaPTOp6KPxkkB0wDQYJKoZIhvcNAQEL
    BQAwgZQxCzAJBgNVBAYTAkVHMRMwEQYDVQQIDApBbGV4YW5kcmlhMRMwEQYDVQQH
    DApBbGV4YW5kcmlhMQ0wCwYDVQQKDARBdG9zMQ8wDQYDVQQLDAZEZXZPcHMxJTAj
    BgkqhkiG9w0BCQEWFm1haG1vdWRrMTAwMEBnbWFpbC5jb20xFDASBgNVBAMMCyou
    bGFiYmkubGFiMB4XDTI0MDkwODE3MzIxNloXDTI1MDkwODE3MzIxNlowgZQxCzAJ
    BgNVBAYTAkVHMRMwEQYDVQQIDApBbGV4YW5kcmlhMRMwEQYDVQQHDApBbGV4YW5k
    cmlhMQ0wCwYDVQQKDARBdG9zMQ8wDQYDVQQLDAZEZXZPcHMxJTAjBgkqhkiG9w0B
    CQEWFm1haG1vdWRrMTAwMEBnbWFpbC5jb20xFDASBgNVBAMMCyoubGFiYmkubGFi
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyVbdzPTq575v5BvtUbjP
    oSckg4VmBBiqRAdbuBswxBuXnmMh4zBGjxV7NmelAtoJmGwC4KHsRd4iO9ShanVi
    0aZm+iiao4sy1iH734scmWsXFaa/wFK3hhYD2MQE1XlAuTBJ7bqOHBt9AIaXUSAq
    ByO/QnnaD1TMrCJI5Zsfpkce43F0b4cdp12TvRqIJR4ryqAiV6wf4ESi/v6unO+0
    Yi4ySg/XeeNBexZmgq3eXzf/jEkDkRzPZiqOgr0GMWXsjFly/o8X+QenTtg4eYwt
    56MsBSgRFXdXhIbqKaSvrLszag8HU0DLwDuAOVpZqfsA9h1/0pSC5A+zehT/TA4w
    KIe4Ssa2GpFJ+iQ743kobEXuOw0yferAXXz0tLG2DJVttOANhDhdkOTiJ9gNsgro
    J+J2bGG2HqYE2i95Fef7ZXiH9Gvhij5wWz+xn/e89VvnKQZS1z+oElTdzzsAsEba
    qClQQ/9iEPo2vWm7TEBLsgCxxBlDKrb5C/wKpTVfj5FXzCm4e+WnuliNAgbQhp/M
    RVocxnisk/PVd4U5zjKV/v1jYQ11ecVmRcmKtV35oRybjE6SU4C5uEGTTqsq976/
    BKplpYccHWriP6fyCBcCKoNnZgKjzcZl0HF5+LeLnyP0GYQ4GaAdA5aJW2YIZCFE
    A1aCYYz6JvA2PnJ4AY+rxWECAwEAAaOBpjCBozAJBgNVHRMEAjAAMAsGA1UdDwQE
    AwIFoDBqBgNVHREEYzBhgglsYWJiaS5sYWKCCyoubGFiYmkubGFighFqZW5raW5z
    LmxhYmJpLmxhYoIPc29uYXIubGFiYmkubGFigg9uZXh1cy5sYWJiaS5sYWKCEnJl
    Z2lzdHJ5LmxhYmJpLmxhYjAdBgNVHQ4EFgQUWp0Ly6fZcBMHlrb5/PaHkwI0Ux0w
    DQYJKoZIhvcNAQELBQADggIBAEH3VMShHNu1sRteeSuFPtt0Tzi/+9uOtZtKviQY
    xpEStTjIKYleG1eRSmRCTPUJIseMzela694YZGiJucs7Nz+wGyS13cRGrmAK+A5I
    pA4fzcVqUvbvTwMgTlILQAUa1U1ixIq5yBsk5h58HhzBB5OeHeVAyqs57cjiZwVb
    hUlu3QnFae1J01DJGrVTK11KtTlvc27o0M5VDoDFTRJp3GHlk7Ga6RUhEwrW7dL5
    xiwWxlnYLrLZcAVztER05GcS+VRf2abm5JY+LzIp4uBuA0C0LWsfm7RpurjjwzW8
    emIrn6IDHcpQlMNLBRW5HGep8oZMZkO7dD2+ej2Qt/QQyBSc1iDHL2V3XUoaPzcF
    Abj3aQrnB+1G0cbCbMY3WXe++Aj1ACkmi5OZFocIAkrTEZ7sjQX36ZNJOyEn/Sif
    LzF0yp9AFJywzDdsmZq/xPXP2+/U8OTRFsiRqWib4CWPrkSw8tdLiFDjK/NToLJu
    eRGVADaby2uNqR05v3XJ0l7YuTxiigEcpue2+ZhYfyP4dXQboMq+BF+pKWi1MeMy
    GHMAD+Xl4ud7YZbfCIDUOj6LiCDxuMbBQ1G7KhIxGYarf6yFB++5Wb7LulA4KN47
    IKwvz0dknlWAut2UiN8bLj/DTq0n91Hwtk+m4wMnqeybOzlyyg/8iSrwBTtb88VM
    cwWj
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: kube-system
data:
  cert_install.sh: |
    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/wild.crt &&
    echo "$TRUSTED_CERT" > /etc/ssl/certs/wild.crt &&
    update-ca-certificates &&
    systemctl restart containerd
  hosts.sh: |
    echo "52.166.234.158 registry.labbi.lab" >> /etc/hosts
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: nodes-injector
  labels:
    k8s-app: nodes-injector
spec:
  selector:
    matchLabels:
      k8s-app: nodes-injector
  template:
    metadata:
      labels:
        k8s-app: nodes-injector
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: cert-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(CERT_SCRIPT)]
          image: debian
          env:
            - name: TRUSTED_CERT
              valueFrom:
                configMapKeyRef:
                  name: trusted-ca
                  key: cert.crt
            - name: CERT_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: cert_install.sh
          securityContext:
            privileged: true
        - name: host-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(HOSTS_SCRIPT)]
          image: debian
          env:
            - name: HOSTS_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: hosts.sh
          securityContext:
            privileged: true
      containers:
        - name: wait
          image: k8s.gcr.io/pause:3.1
