---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-ca
  namespace: kube-system
data:
  cert.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFEDCCA/igAwIBAgIUHpu/SKEO0PZFL3yaJOkg9PV4hzgwDQYJKoZIhvcNAQEL
    BQAwgd0xFDASBgNVBAMMCyoubGFiYmkubGFiMRowGAYDVQQDDBFqZW5raW5zLmxh
    YmJpLmxhYjEYMBYGA1UEAwwPc29uYXIubGFiYmkubGFiMRIwEAYDVQQDDAlsYWJi
    aS5sYWIxGDAWBgNVBAMMD25leHVzLmxhYmJpLmxhYjEbMBkGA1UEAwwScmVnaXN0
    cnkubGFiYmkubGFiMQswCQYDVQQGEwJFRzETMBEGA1UECAwKQWxleGFuZHJpYTET
    MBEGA1UEBwwKQWxleGFuZHJpYTENMAsGA1UECgwEQXRvczAeFw0yNDA5MDgyMDIy
    MjJaFw0zNDA5MDYyMDIyMjJaMIHdMRQwEgYDVQQDDAsqLmxhYmJpLmxhYjEaMBgG
    A1UEAwwRamVua2lucy5sYWJiaS5sYWIxGDAWBgNVBAMMD3NvbmFyLmxhYmJpLmxh
    YjESMBAGA1UEAwwJbGFiYmkubGFiMRgwFgYDVQQDDA9uZXh1cy5sYWJiaS5sYWIx
    GzAZBgNVBAMMEnJlZ2lzdHJ5LmxhYmJpLmxhYjELMAkGA1UEBhMCRUcxEzARBgNV
    BAgMCkFsZXhhbmRyaWExEzARBgNVBAcMCkFsZXhhbmRyaWExDTALBgNVBAoMBEF0
    b3MwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDD2RA/gefe9d4Mj7qh
    Pz+oGrAepa0ZkCBWk0bx7dYdkzmjUwuWKuYr2zt4gY7KGkMboP2tcp3CRXvGxOkp
    FL4NafTh3E2ynQYZzKpwpNtg4yyMQsMlw8iSrDFMKa6M6o7hMmlLKnSx2tU/T3x1
    s7XMlC5EdhgXIpud6DWLnmsdvpyNIPb+rC2DULjzngK42qJd7xhIUTQZqjaFp8Ee
    mHsQ0gB2O3G7wALQ4tnnok7d0jXZQRaOz7FzZU3erl4xXF5o+3yAykkgN6bAZXGU
    4sALk//tlJEwwYeT253M7kA43GPvhHOEC7hCffJTr/opZqk178toWHZ2QqkobrFY
    eNR7AgMBAAGjgcUwgcIwHQYDVR0OBBYEFHiUBKM7BD6w7BC4LclPj6MDox7JMB8G
    A1UdIwQYMBaAFHiUBKM7BD6w7BC4LclPj6MDox7JMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAgEBMF8GA1UdEQRYMFaCCyoubGFiYmkubGFighFqZW5raW5z
    LmxhYmJpLmxhYoIPc29uYXIubGFiYmkubGFigg9uZXh1YS5sYWJiaS5sYWKCEnJl
    Z2lzdHJ5LmxhYmJpLmxhYjANBgkqhkiG9w0BAQsFAAOCAQEArNFYKqEkccfPsXA5
    Z4e2FTxrOgwrQWzsZmJoY8TDkmJRI4r3AeNbxtxtlEWiePTSbfff6FO8W+N5V7xe
    3wmiHfjN3OC/kSQD13LGl0Sqj5WOrNR5SqPkwtoTNhn4NLHYeCHJPMIW6pbGQubL
    p5MFyeGPo71kZ28+TUSNB9+z3il6LYIAtY6fzDaC+vPDij9pPnHOKZ60tKcOgEtd
    UIky2Zl7CFofsyBLifMMuOW9dCjy91OC3dxOg756RP85Q16kBUaOSHpkahEgp7Fg
    8D55T9/reugT/hXOFsAd9hbZKHXp9u6PrnNgA2FYUCIZswtETKovAcKsBUn+mACQ
    My9zKQ==
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: kube-system
data:
  cert_install.sh: |
    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/wild.crt &&
    echo "$TRUSTED_CERT" > /etc/ssl/certs/wild.crt &&
    update-ca-certificates &&
    systemctl restart containerd
  hosts.sh: |
    echo "51.144.158.233 registry.labbi.lab" >> /etc/hosts
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: nodes-injector
  labels:
    k8s-app: nodes-injector
spec:
  selector:
    matchLabels:
      k8s-app: nodes-injector
  template:
    metadata:
      labels:
        k8s-app: nodes-injector
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: cert-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(CERT_SCRIPT)]
          image: debian
          env:
            - name: TRUSTED_CERT
              valueFrom:
                configMapKeyRef:
                  name: trusted-ca
                  key: cert.crt
            - name: CERT_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: cert_install.sh
          securityContext:
            privileged: true
        - name: host-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(HOSTS_SCRIPT)]
          image: debian
          env:
            - name: HOSTS_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: hosts.sh
          securityContext:
            privileged: true
      containers:
        - name: wait
          image: k8s.gcr.io/pause:3.1
