---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-ca
  namespace: kube-system
data:
  cert.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEMjCCAxqgAwIBAgIUAhtY38bNcV1Y2vtKVHpAYCcDU/4wDQYJKoZIhvcNAQEL
    BQAwgZsxCzAJBgNVBAYTAkVHMRMwEQYDVQQIDApBbGV4YW5kcmlhMRMwEQYDVQQH
    DApBbGV4YW5kcmlhMQ0wCwYDVQQKDARBdG9zMQ8wDQYDVQQLDAZEZXZPcHMxGzAZ
    BgNVBAMMEnJlZ2lzdHJ5LmxhYmJpLmxhYjElMCMGCSqGSIb3DQEJARYWbWFobW91
    ZGsxMDAwQGdtYWlsLmNvbTAeFw0yNDA5MDgxODQxMzdaFw0yNTA5MDgxODQxMzda
    MIGbMQswCQYDVQQGEwJFRzETMBEGA1UECAwKQWxleGFuZHJpYTETMBEGA1UEBwwK
    QWxleGFuZHJpYTENMAsGA1UECgwEQXRvczEPMA0GA1UECwwGRGV2T3BzMRswGQYD
    VQQDDBJyZWdpc3RyeS5sYWJiaS5sYWIxJTAjBgkqhkiG9w0BCQEWFm1haG1vdWRr
    MTAwMEBnbWFpbC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDj
    LyEjcZ5YWAucb3emPGBYm1AtW2kx534Yt+zpMBIEuadPrTgUYRnod6Z5bm+OESkN
    ZulAMh5s2cH6fvOvEe30cKPVVJx2lalSKGyOR0KNmdtQuD/C4r85OcHf4S2qXQwN
    gLCGUPAQSNmzuGTI/nE9KMBpCXPfmTSL/46zwpp2/AtuBDSusr1DA75b+5DvBAW3
    gwlsAFjXA+E2BrcT3i36TSpK6H/dVC4EdxttXZ3+4J309nmPCqY1QJnrKvnSlPAC
    aegEafk05I47PPGwxfLErkFkLQL5d7B8QK2Ab1VGD7TYxm+elc/+YElkXWPjuCrL
    HANbS+hty/HlG0cDdTCDAgMBAAGjbDBqMB8GA1UdIwQYMBaAFJBfAXZZu2GV240N
    c9J7xh5xp6nYMAkGA1UdEwQCMAAwHQYDVR0RBBYwFIIScmVnaXN0cnkubGFiYmku
    bGFiMB0GA1UdDgQWBBR59BVxncbq3XQMa5XezVfI4I3VTTANBgkqhkiG9w0BAQsF
    AAOCAQEAkcO+MvWt7GBy3Lh9IPMAeKFaiq53Yp54ijxfZFoUBtC9MEykM48d1dXA
    ZQkIdHG3tlxNqWRHAVvSFiAUnoKcqbqq1EIr120FcdHBj+Q+ZS2J6D8VianRIhqA
    GnzzJpuhzEixXmgoFf9IlwLG8fziU5zwgDSPAI5QVi0vaThldjIX9eQENrwdoG1e
    wiLvmt55be1NEWsxmRFJZPSgveil03mG3Gr+PPa5aYkVG/HJpfmmgvNA3bSKmsqF
    yRC7yAuMTCSnWNKCsfJ3kCLQSOzl9Rgv94mS5yCJxz6tM7I1NsguefYKYL4pIo6d
    j+2oANQZiW+VHqX3GhGnBzlHSVaIVg==
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
  namespace: kube-system
data:
  cert_install.sh: |
    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/cert.crt &&
    echo "$TRUSTED_CERT" > /etc/ssl/certs/cert.crt &&
    update-ca-certificates &&
    systemctl restart containerd
  hosts.sh: |
    echo "52.166.234.158 registry.labbi.lab" >> /etc/hosts
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: nodes-injector
  labels:
    k8s-app: nodes-injector
spec:
  selector:
    matchLabels:
      k8s-app: nodes-injector
  template:
    metadata:
      labels:
        k8s-app: nodes-injector
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: cert-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(CERT_SCRIPT)]
          image: debian
          env:
            - name: TRUSTED_CERT
              valueFrom:
                configMapKeyRef:
                  name: trusted-ca
                  key: cert.crt
            - name: CERT_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: cert_install.sh
          securityContext:
            privileged: true
        - name: host-node
          command: [nsenter]
          args: [--mount=/proc/1/ns/mnt, --, sh, -c, $(HOSTS_SCRIPT)]
          image: debian
          env:
            - name: HOSTS_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: scripts
                  key: hosts.sh
          securityContext:
            privileged: true
      containers:
        - name: wait
          image: k8s.gcr.io/pause:3.1
