---
name: publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java: ['17']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mahmoudk1000
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: adopt
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package -DskipTests
      - name: Build the hello-docker Docker image
        run: |-
          docker build -f Dockerfile.petclinic . --tag ghcr.io/mahmoudk1000/petclinic:new
          docker push ghcr.io/mahmoudk1000/petclinic:new
